#!/bin/sh

destunitdir=${1:-/tmp}

# Do nothing if target is disabled
[ -e /etc/systemd/system/multi-user.target.wants/dhcp_probe.target ] || exit 0

[ -f /etc/sysconfig/dhcp_probe ] && . /etc/sysconfig/dhcp_probe

if [ -d $destunitdir/dhcp_probe.target.wants ]; then
	rm -f $destunitdir/dhcp_probe.target.wants/dhcp_probe@*.service
else
	mkdir -p $destunitdir/dhcp_probe.target.wants
fi

for nic in $INTERFACES; do
	[ -L $destunitdir/dhcp_probe.target.wants/dhcp_probe@$nic.service ] && \
		continue
	ln -s /lib/systemd/system/dhcp_probe@.service \
		$destunitdir/dhcp_probe.target.wants/dhcp_probe@$nic.service
done
